development:
  adapter: mysql
  encoding: utf8
  database: niget_development
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: niget
  pool: 5
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
